### ISSUE TITLE
Allow manifest.json as the entry point

### ISSUE THREAD

**Issue by fregante** [abhijithvijayan/wext-manifest-loader#8]
Imagine having just one entry point as your webpack configuration:

```js
{
	entry: 'manifest.json',
	output: {
		path: path.join(__dirname, 'dist'),
		filename: '[name].[ext]'
	},
	module: {
		rules: [
			{
				test: /\.html$/,
				use: [
					'extract-loader',
					'html-loader'
				]
			},
			{
				test: /\.css$/,
				use: [
					'file-loader', 
					'extract-loader',
					'css-loader'
				]
			}
		]
	},
	plugins: {
		new WextEntryPlugin()
	}
}
```

This is possible [in parcel](https://github.com/kevincharm/parcel-plugin-web-extension) and [in rollup](https://github.com/bumble-org/rollup-plugin-chrome-extension) with plugins. They automatically find all the related files starting from manifest.json:

- background scripts
- content scripts
- option pages and their dependencies
- popup pages and their dependencies
- etc

This might be a starting point: https://github.com/erikdesjardins/inert-entry-webpack-plugin

Such a plugin, if possible in webpack, would definitely be of interest to me and I'd use it in Refined GitHub.

**Comment by abhijithvijayan** [comment]
I can only build a new plugin for this. I have thought about it as well.

Few projects depend on this loader and it is difficult to ask them to migrate again.

**Comment by abhijithvijayan** [comment]
Cool.

I think this can be done with a little bit of effort.

I am currently engaged in a freelance work.

Will work on it in parallel if possible.
Hope it works.

**Comment by abhijithvijayan** [comment]
I am having my last semester exams soon. After that I will spend time on this issue and build a project as per the need.

Thanks.

**Comment by fregante** [comment]
It looks like someone wrote it, not sure if it works though: https://github.com/jsmnbom/webextension-manifest-loader

**Comment by abhijithvijayan** [comment]
Oh cool, it is sort of based on this project as it says so.

I am not sure if its a good idea to use a loader to do all that. Maybe a plugin seems to be a better choice for that.

And if it works, there is no need to write new one right?

**Comment by fregante** [comment]
I'm not very familiar with how Webpack works, my only complaint with it at this moment is that it needs both a loader **and** a plugin, but that might not be avoidable.

**Comment by abhijithvijayan** [comment]
I think the issue with the above mentioned loader is that, it relies on the plugin.

The solution I think is to build a plugin that does all the work with the help of the loaders(for the assets)

That way, you only have to add loaders for the different types of assets and set the manifest as entry point and the plugin to handle all those.


Exactly like the example you suggested https://github.com/abhijithvijayan/wext-manifest-loader/issues/8#issue-618433790

**Comment by abhijithvijayan** [comment]
I didnt really get time to work on this. Did you find something that works by the way?
