### ISSUE TITLE
Ability to emit keys or values based on enviroment

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/wext-manifest-loader#9]
The `manfest.json` can't accept values based on conditions.
Like the vender prefixes, we can probably add `__dev__` and `__prod__` flag for keys that are to be emitted in development only.

This was raised in [this question](https://github.com/ThaneshR/web-extension-starter/commit/514ec23e396634a87665c97f21ee995a19cc698c#commitcomment-39269108) by @ThaneshR

when this is implemented, users could try like this
```
{
...
 "__dev__content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'",
 "__prod__content_security_policy": "script-src 'self'; object-src 'self'",
...
}
```
and produce the necessary keys based on enviroment.

**Comment by abhijithvijayan** [comment]
npm throwing errors on publishing
```
...
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/wext-manifest-loader
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
...
```

**Comment by abhijithvijayan** [comment]
Released in `2.0.0`

**Comment by abhijithvijayan** [comment]
@ThaneshR Could you test and see if this makes it possible?

Like you said, this is useful for **Content Security Policy** and even other fields.

Ref: https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval

**Comment by ThaneshR** [comment]
@abhijithvijayan I migrated my extension and tested it, it works.

I'm not sure why but now when I remove the `unsafe-eval` in `content-security-policy` for `dev` mode, the app still works. I checked the compiled manifest and `unsafe-eval` is not present.

I poked around but I can't figure out what changed, maybe the newer version of `webpack` is no longer using `eval` is the best conclusion I can come up with.

Thanks for the quick turnaround.

**Comment by abhijithvijayan** [comment]
@ThaneshR i added that `unsafe-eval` some time back in `kutt-extension` for some error I think.

Thanks Anyway, it's a good suggestion. Different Development and Production keys might not be everyone's use case. But it is kinda nice to have that as well.

Anyway, closing this for now.

**Comment by ThaneshR** [comment]
@abhijithvijayan I figured out why you don't need `unsafe-eval` in `dev` mode anymore.

It's because you added this line in the `webpack` config to disable `devtool` on April 17: 
https://github.com/abhijithvijayan/web-extension-starter/blob/react-typescript/webpack.config.js#L49

And `devtool` is the reason `webpack` uses `eval`: https://stackoverflow.com/a/50405809/3642636

I originally pulled your repo in March, hence why my repo before the migration was using `eval` and not after.

File this under: _#good-to-know :smile:

**Comment by abhijithvijayan** [comment]
@ThaneshR Oh cool!

It was to fix another issue a user raised.

Could you do a PR to the starter that removes all the prefixes and `unsafe-eval` as well, so that no transformation is required for the content security policies?

So basically left with a single line for CSP.
